from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

out = 'assignment.pdf'
c = canvas.Canvas(out, pagesize=A4)
width, height = A4

c.setFont('Helvetica-Bold', 16)
c.drawString(48, height - 72, 'Static Online Shopping Website — Assignment')

c.setFont('Helvetica', 11)
text = c.beginText(48, height - 100)
text.setLeading(14)
text.textLines([
    'Author: (Repository files included in this workspace)',
    f'Date: {datetime.now().strftime("%Y-%m-%d")}',
    '',
    'Pages included in this assignment:',
    '- home.html — Home page with featured items and navigation',
    '- catalogue.html — Product catalogue with simple product cards',
    '- cart.html — Static cart example and totals',
    '- login.html — Login form (no JavaScript, simple form)',
    '- signup.html — Registration form (no JavaScript, simple form)',
    '',
    'Notes:',
    '- Pages use a shared stylesheet: styles.css',
    "- No JavaScript files were added; the site is intentionally basic.",
    '',
    'How to view locally: open the HTML files (e.g., open home.html) in a browser.',
    '',
    'Deployment (GitHub Pages): push these files and enable Pages in the repository settings or place them under a docs/ folder and enable Pages from the repository main branch.',
    '',
    'This PDF was generated by a small script included with the assignment. Thank you.'
])

c.drawText(text)

c.save()
print('Created', out)